name: 'Saplings Solr'
description: 'Enables and configures essential modules and base search view with facets.'
type: 'Site config'

install:
  - search
  - search_api
  - facets
  - search_api_solr
  - search_api_pantheon
  - configurable_views_filter_block
  - better_exposed_filters
  - search_api_solr_admin
  - tour

config:
  import:
    search_api: '*'
    search_api_solr: '*'
